version: "3"

services:
    redis-db:
        image: redis:7
        ports:
            - "6379:6379"
        volumes:
          - ./data:/data
        command: ["--save", "1", "1"]
    
    flask-app:
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - redis-db
        image: vigneshwinner/flask_iss_tracker:1.0
        ports:
            - "5000:5000"

